name: C++ CI

on:
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: apt-get update && apt-get install -y build-essential cmake g++

      - name: Create build directory
        run: mkdir build && cd build

      - name: Configure CMake
        working-directory: ./build
        run: cmake ..

      - name: Build with Cmake
        working-directory: ./build
        run: cmake --build .

      - name: Run CTest
        working-directory: ./build
        run: ctest --verbose
      
      - name: Test the application
        working-directory: ./build
        run: ./my_cpp_app
